/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Access: typeof import('./../src/components/access/index.vue')['default']
    BaseLoading: typeof import('./../src/components/base-loading/index.vue')['default']
    CarbonLanguage: typeof import('./../src/components/icons/carbon-language.vue')['default']
    CarbonMoon: typeof import('./../src/components/icons/carbon-moon.vue')['default']
    CarbonSun: typeof import('./../src/components/icons/carbon-sun.vue')['default']
    ChaseSpin: typeof import('./../src/components/base-loading/spin/chase-spin.vue')['default']
    CubeSpin: typeof import('./../src/components/base-loading/spin/cube-spin.vue')['default']
    DocLink: typeof import('./../src/components/doc-link/index.vue')['default']
    DotSpin: typeof import('./../src/components/base-loading/spin/dot-spin.vue')['default']
    FooterLinks: typeof import('./../src/components/footer-links.vue')['default']
    GithubLink: typeof import('./../src/components/github-link/index.vue')['default']
    PageContainer: typeof import('./../src/components/page-container/index.vue')['default']
    PlaneSpin: typeof import('./../src/components/base-loading/spin/plane-spin.vue')['default']
    PreloaderSpin: typeof import('./../src/components/base-loading/spin/preloader-spin.vue')['default']
    PulseSpin: typeof import('./../src/components/base-loading/spin/pulse-spin.vue')['default']
    RectSpin: typeof import('./../src/components/base-loading/spin/rect-spin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLang: typeof import('./../src/components/select-lang/index.vue')['default']
    TokenProvider: typeof import('./../src/components/token-provider/index.vue')['default']
    UserAvatar: typeof import('./../src/components/user-avatar/index.vue')['default']
  }
}
