import type { LayoutSetting } from '~@/stores/app'

export default {
  title: 'Antdv Pro',
  theme: 'light',
  logo: '/logo.svg',
  collapsed: false,
  drawerVisible: false,
  colorPrimary: '#1677FF',
  layout: 'mix',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixedSider: true,
  splitMenus: false,
  header: true,
  menu: true,
  menuHeader: true,
  footer: false,
  colorWeak: false,
  multiTab: true,
  multiTabFixed: false,
  keepAlive: true,
  headerHeight: 48,
  copyright: '爱吧烟雨2023',
} as LayoutSetting
