// Generated by nitro
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/': {
      'default': Awaited<ReturnType<typeof import('../../routes/index').default>>
    }
    '/login': {
      'post': Awaited<ReturnType<typeof import('../../routes/login.post').default>>
    }
  }
}
export {}